allowBuilds:
  '@sentry-internal/node-cpu-profiler': true
  '@sentry/cli': true
  esbuild: true
  msw: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@sentry-internal/node-cpu-profiler'
  - '@sentry/cli'
  - '@signmax/config'
  - esbuild
  - msw
  - unrs-resolver
