services:
  app:
    image: harbor.signmax.cloud/public/devcontainer:rails-4.0.6-31@sha256:6dfa113b34bb3785a5931e23750f28341bf62d48bbee7e45133b9fcef5a59917
    volumes:
      - ..:/workspaces/remix-base:cached
    shm_size: "1gb"
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
