services:
  app:
    image: harbor.signmax.cloud/public/devcontainer:35@sha256:c2c72d7655656ce2f6eae44047526f0fb8774115aab4d2907f78e28000c69611
    volumes:
      - ..:/workspaces/remix-base:cached
    shm_size: "1gb"
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
